In [13]:
import numpy as np

In [14]:
# Create an array with 6 elements between 1 and 10
array1 = np.linspace(1,10,6)
array1

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

Task: Perform array slicing

In [15]:
# Perform array slicing
arr = np.random.randint(40,80,8)
print(arr)

arr1 = arr[4:8]
print(arr1)
arr2 = arr[:1:-1]
arr2

[42 69 65 59 61 55 66 65]
[61 55 66 65]


array([65, 66, 55, 61, 59, 65], dtype=int32)

Create an array of number from 1  to 10 and print only even numbers from that

In [ ]:
# Create an array of number from 1  to 10 and print only even numbers from that array
arr = np.arange(1,11)
print(arr)
even_arr = arr[arr % 2 == 0]
print(even_arr)

# odd numbers
odd_arr = arr[arr % 2 != 0]
odd_arr


[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]


array([1, 3, 5, 7, 9])