In [1]:
import numpy as np

In [2]:
# defining list as an numpy array 
list = [1,2,3,4,5] 
array = np.array(list)
array

array([1, 2, 3, 4, 5])

In [ ]:
# Or tuple (also dict as well)
tuple = (9,8,5,6,3,1) 
array = np.array(tuple)
array

array([9, 8, 5, 6, 3, 1])

In [4]:
# 1D array
array1 = np.array([1,2,3,4,5])

# 2D array
array2 = np.array([[1,2], [3,4]])

# 3D array
array3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print("1D array:",array1)
print("2D array:",array2)
print("3D array:",array3)

1D array: [1 2 3 4 5]
2D array: [[1 2]
 [3 4]]
3D array: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
# Creating from scratch

# array filled with zeros only
array1 = np.zeros(20)
array1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [6]:
# array filled with ones only
array2 = np.ones(20)
array2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [11]:
# array of numbers using arange
array3 = np.arange(20,50,3) # start,stop, steps
a1 = np.arange(100,252)
# array3
a1

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
       217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251])

In [12]:
# array using linspace
array4 = np.linspace(4,10,5) #start,end, no. of elements 
b1 = np.linspace(40,100)
# array4
b1

array([ 40.        ,  41.2244898 ,  42.44897959,  43.67346939,
        44.89795918,  46.12244898,  47.34693878,  48.57142857,
        49.79591837,  51.02040816,  52.24489796,  53.46938776,
        54.69387755,  55.91836735,  57.14285714,  58.36734694,
        59.59183673,  60.81632653,  62.04081633,  63.26530612,
        64.48979592,  65.71428571,  66.93877551,  68.16326531,
        69.3877551 ,  70.6122449 ,  71.83673469,  73.06122449,
        74.28571429,  75.51020408,  76.73469388,  77.95918367,
        79.18367347,  80.40816327,  81.63265306,  82.85714286,
        84.08163265,  85.30612245,  86.53061224,  87.75510204,
        88.97959184,  90.20408163,  91.42857143,  92.65306122,
        93.87755102,  95.10204082,  96.32653061,  97.55102041,
        98.7755102 , 100.        ])