In [1]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [2]:
# 1.Slice and print every third element starting from index 1.
sliced_arr = arr[1::3]
sliced_arr

array([10, 25, 40])

In [3]:
# 2. Print the last 4 elements using negative indexing.
last_four_elements = arr[-4:]
last_four_elements

array([35, 40, 45, 50])

In [9]:
# 3.Replace the values at even indices with -1.
even_values = arr.copy()
even_values[1::2] = -1
even_values

array([ 5, -1, 15, -1, 25, -1, 35, -1, 45, -1])

In [10]:
# 4.Use fancy indexing to extract the values at positions [2, 4, 6, 8].
indices = [2, 4, 6, 8]
fancy_values = arr[indices]
fancy_values

array([15, 25, 35, 45])